choco install -y 7zip.install
choco install -y azure-cli
choco install -y bruno
choco install -y discord
choco install -y docker-desktop
choco install -y dotnet-sdk
choco install -y ffmpeg
choco install -y gimp
choco install -y git
choco install -y git-fork
choco install -y golang
choco install -y microsoft-windows-terminal
choco install -y nodejs
choco install -y obsidian
choco install -y pgadmin4
choco install -y postman
choco install -y postgresql
choco install -y powertoys
choco install -y python
choco install -y spotify
choco install -y terraform
choco install -y tree
choco install -y visualstudio2022community
choco install -y vlc
choco install -y vscode
choco install -y zoom
