choco install -y 7zip.install
choco install -y docker-desktop
choco install -y git
choco install -y git-fork
choco install -y microsoft-windows-terminal
choco install -y nodejs
choco install -y postman
choco install -y powertoys
choco install -y spotify
choco install -y visualstudio2022community
choco install -y vscode
